config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :dashboards, only: :index

  resources :courses, shallow: true do
    resources :academic_terms do
      resources :course_subjects do
        resources :tutorials do
          resources :assessments do
            resources :tasks do
              resources :marks, only: [:edit, :update]
            end
            resources :grades, only: :update
          end
        end
      end
    end

    resources :course_sessions do
      resources :class_groups
      resources :admissions, only: [:new, :create]
    end
  end

  resources :admissions, only: :index
  resources :students, except: [:new, :create]

  resources :teachers
  resources :people

  class NewSpeakMain
    def self.matches?(request)
      request.host.match /\A(www.|)newspeak.com\z/i
    end
  end

  constraints NewSpeakMain do
    resources :accounts, only: [:new, :create]
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
	# Assocations

  belongs_to  :assessment
  belongs_to  :institute
  has_many    :task_results

  # Validations

  validates :assessment, presence: true
  validates :institute, presence: true
  
  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :assessment_id }
  validates :due_date, presence: true
  validates :description, presence: true
  validates :maximum_marks, presence: true, numericality: true
  validates :weightage, presence: true, numericality: { minimum: 0, maximum: 100 }
  validate  :ensure_total_tasks_marks_does_not_exceed_assessment_marks

  # Nested Attributes

  accepts_nested_attributes_for :task_results


  # Instance Methods
  def ensure_total_tasks_marks_does_not_exceed_assessment_marks
    other_tasks = assessment.tasks if assessment
    total_marks = 0
    other_tasks.try(:each) do |task|
      if task.id == self.id
        total_marks += maximum_marks * (weightage / 100)
      else
        total_marks += task.maximum_marks * (task.weightage / 100)
      end
    end

    if assessment && (total_marks > assessment.maximum_marks)
      errors.add(:maximum_marks, "sum of all marks of tasks (#{total_marks}) should be less than maximum marks (#{assessment.maximum_marks}).")
    end        
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def new
		@assessment = current_account.assessments.find(params[:assessment_id])
		@task = @assessment.tasks.build
		authorize @task
	end

	def create
		@assessment = current_account.assessments.find(params[:assessment_id])
		@task = @assessment.tasks.build(task_params)
		@task.institute = current_account
		authorize @task
		
		@assessment.assessment_results.each do |result|
			@task.task_results.build(marks_obtained: 0.0, student: result.student, assessment_result: result, institute: current_account)
		end

		if @task.save
			redirect_to @assessment, notice: "#{@task.name} was added to the assessment"
		else
			p @task.errors
			render :new
		end
	end

	def edit
		@task = current_account.tasks.find(params[:id])
		authorize @task
		@assessment = @task.assessment
	end

	def show
		@task = current_account.tasks.find(params[:id])
		authorize @task
		@assessment = @task.assessment
	end

	def update
		@task = current_account.tasks.find(params[:id])
		authorize @task
		@assessment = @task.assessment
		if @task.update(task_params)
			redirect_to @task, notice: "Task was updated"
		else
			render :edit
		end
	end

	private

	def task_params
		params.require(:task).permit(:name, :description, :due_date, :maximum_marks, :weightage)
	end
end

app/views/tasks/_form.html.erb
<div class="row">
	<div class="col-sm-8">
			<%= f.input :name, placeholder: 'Task Name' %>
	</div>

	<div class="col-sm-4">
		<%= f.input :due_date, placeholder: 'Task Due Date', as: :date_picker %>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
			<%= f.input :description, placeholder: 'Task Description' %>
	</div>
</div>

<div class="row">
	<div class="col-sm-6">
			<%= f.input :maximum_marks, placeholder: 'Maximum Marks', as: :string %>
	</div>

	<div class="col-sm-6">
		<%= f.input :weightage, placeholder: 'Weightage', as: :string %>
	</div>
</div>

app/views/tasks/edit.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li> <%= link_to 'Dashboard', dashboards_path %> </li>
	  <li> <%= link_to @assessment.tutorial.class_group.name, @assessment.tutorial.class_group %> </li>
	  <li> <%= link_to @assessment.tutorial.course_subject.title, @assessment.tutorial.course_subject %> </li>
	  <li> <%= link_to @assessment.title, @assessment %> </li>
	  <li class="active"><%= @task.name %></li>
	</ol>
<% end %>

<div class="row">
	<div class="col-sm-8">
		<%= simple_form_for(@task) do |f| %>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Edit Task <%= @task.name %></h3>
				</div>

				<div class="panel-body">
					<%= render "form", f: f %>
				</div>
				<div class="panel-footer">
					<%= f.button :submit, "Save Task" %>
				</div>
			</div>
		<% end %>
	</div>
	<div class="col-sm-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Info</h3>
			</div>
			<div class="panel-body"></div>
			<div class="panel-footer"></div>
		</div>		
	</div>
</div>

app/views/tasks/marks.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li> <%= link_to 'Dashboard', dashboards_path %> </li>
	  <li> <%= link_to @assessment.teaching_assignment.class_group.course_session.name, @assessment.teaching_assignment.class_group.course_session %></li>
	  <li> <%= link_to @assessment.teaching_assignment.class_group.name, @assessment.teaching_assignment.class_group %></li>
	  <li> <%= link_to @assessment.title, @assessment %></li>
	  <li class="active"><%= @task.name %></li>
	</ol>
<% end %>

<div class="row">
	<div class="col-sm-8">
			<%= simple_form_for(@task, url: marks_update_task_path(@task)) do |f| %>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">Results</h3>
					</div>

					<table class="table table-condensed">
						<thead>
							<tr>
								<td>#</td>
								<td>Student Name</td>
								<td>Admission #</td>
								<td>Marks Obtained</td>
							</tr>
						</thead>

						<tbody>
							<%= f.simple_fields_for :task_results  do |result| %>
								<tr>
									<td><%= result.index + 1 %></td>
									<td><%= result.object.student.name %></td>
									<td><%= result.object.student.admission_number %></td>
									<td><%= result.input :marks_obtained, as: :string, label: false %></td>
								</tr>
							<% end %>
						</tbody>
					</table>

					<div class="panel-footer">
						<%= f.button :submit, "Update Marks" %>
					</div>
				</div>
			<% end %>
	</div>
	<div class="col-sm-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><%= @task.name %></h3>
			</div>

			<div class="panel-body">
				<div class="list-group">
			    <h6 class="list-group-item-heading">Description</h6>
			    <p class="list-group-item-text"><%= @task.description %></p>
				</div>

				<div class="list-group">
			    <h6 class="list-group-item-heading">Due Date</h6>
			    <p class="list-group-item-text"><%= @task.due_date.to_formatted_s(:rfc822) %></p>
				</div>

				<div class="list-group">
			    <h6 class="list-group-item-heading">Weightage</h6>
			    <p class="list-group-item-text"><%= @task.weightage %></p>
				</div>

				<div class="list-group">
			    <h6 class="list-group-item-heading">Maximum Marks</h6>
			    <p class="list-group-item-text"><%= @task.maximum_marks %></p>
				</div>
			</div>

			<div class="panel-footer">
				<%= link_to 'Edit', edit_task_path(@task) %>
			</div>
		</div>
	</div>
</div>

app/views/tasks/new.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li> <%= link_to 'Dashboard', dashboards_path %> </li>
	  <li> <%= link_to @assessment.tutorial.class_group.name, @assessment.tutorial.class_group %> </li>
	  <li> <%= link_to @assessment.tutorial.course_subject.title, @assessment.tutorial.course_subject %> </li>
	  <li> <%= link_to @assessment.title, @assessment %> </li>
	  <li class="active">New Assessment Task</li>
	</ol>
<% end %>

<div class="row">
	<div class="col-sm-8">
		<%= simple_form_for([@assessment, @task]) do |f| %>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">New Task for <%= @assessment.title %></h3>
				</div>

				<div class="panel-body">
					<%= render "form", f: f %>
				</div>
				<div class="panel-footer">
					<%= f.button :submit, "Save Task" %>
				</div>
			</div>
		<% end %>
	</div>
	<div class="col-sm-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Other Tasks</h3>
			</div>
			<div class="panel-body"></div>
			<div class="panel-footer"></div>
		</div>		
	</div>
</div>

app/views/tasks/show.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li> <%= link_to 'Dashboard', dashboards_path %> </li>
	  <li> <%= link_to @assessment.tutorial.class_group.course_session.name, @assessment.tutorial.class_group.course_session %></li>
	  <li> <%= link_to @assessment.tutorial.class_group.name, @assessment.tutorial.class_group %></li>
	  <li> <%= link_to @assessment.title, @assessment %></li>
	  <li class="active"><%= @task.name %></li>
	</ol>
<% end %>

<div class="row">
	<div class="col-sm-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Results</h3>
				</div>

				<table class="table table-condensed">
					<thead>
						<tr>
							<td>#</td>
							<td>Student Name</td>
							<td>Admission #</td>
							<td>Marks Obtained</td>
						</tr>
					</thead>

					<tbody>
						<% @task.task_results.each_with_index do |result, index| %>
							<tr>
								<td><%= index + 1 %></td>
								<td><%= result.student.name %></td>
								<td><%= result.student.admission_number %></td>
								<td><%= result.marks_obtained %></td>
							</tr>
						<% end %>
					</tbody>
				</table>

				<div class="panel-footer">
					<%= link_to 'Update Marks', edit_mark_path(@task) %>
				</div>
			</div>
	</div>
	<div class="col-sm-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><%= @task.name %></h3>
			</div>

			<div class="panel-body">
				<div class="list-group">
			    <h6 class="list-group-item-heading">Description</h6>
			    <p class="list-group-item-text"><%= @task.description %></p>
				</div>

				<div class="list-group">
			    <h6 class="list-group-item-heading">Due Date</h6>
			    <p class="list-group-item-text"><%= l(@task.due_date) %></p>
				</div>

				<div class="list-group">
			    <h6 class="list-group-item-heading">Weightage</h6>
			    <p class="list-group-item-text"><%= @task.weightage %></p>
				</div>

				<div class="list-group">
			    <h6 class="list-group-item-heading">Maximum Marks</h6>
			    <p class="list-group-item-text"><%= @task.maximum_marks %></p>
				</div>
			</div>

			<div class="panel-footer">
				<%= link_to 'Edit', edit_task_path(@task) %>
			</div>
		</div>
	</div>
</div>