config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :dashboards, only: :index

  resources :courses, shallow: true do
    resources :academic_terms do
      resources :course_subjects do
        resources :tutorials do
          resources :assessments do
            resources :tasks do
              resources :marks, only: [:edit, :update]
            end
            resources :grades, only: :update
          end
        end
      end
    end

    resources :course_sessions do
      resources :class_groups
      resources :admissions, only: [:new, :create]
    end
  end

  resources :admissions, only: :index
  resources :students, except: [:new, :create]

  resources :teachers
  resources :people

  class NewSpeakMain
    def self.matches?(request)
      request.host.match /\A(www.|)newspeak.com\z/i
    end
  end

  constraints NewSpeakMain do
    resources :accounts, only: [:new, :create]
  end

end

app/models/academic_term.rb
class AcademicTerm < ActiveRecord::Base
	#Enum

	enum term_type: [:year, :semester, :trimester]

	# Associations

  belongs_to :course
  belongs_to :institute
  has_many :course_sessions
  has_many :course_subjects, inverse_of: :academic_term

  # Validations
  validates :course, presence: true
  validates :institute, presence: true
  validates :term_type, presence: true
  validates :term_class, presence: true, uniqueness: { case_sensitive: false, scope: [:course_id, :institute_id] }
  validates :title, presence: true, uniqueness: { case_sensitive: false, scope: [:course_id, :institute_id] }
  validates :code, presence: true, uniqueness: { case_sensitive: false, scope: [:course_id, :institute_id] }

  # Nested Attributes

  accepts_nested_attributes_for :course_subjects
end

app/controllers/academic_terms_controller.rb
class AcademicTermsController < ApplicationController
	def new
		@course = current_account.courses.find(params[:course_id])
		@term = @course.academic_terms.build
	end

	def create
		@course = current_account.courses.find(params[:course_id])
		@term = @course.academic_terms.build(academic_term_params)
		@term.institute = current_account

		if @term.save
			redirect_to @course, notice: "New term #{@term.title} created"
		else
			render :new
		end
	end

	def edit
		@term = current_account.academic_terms.find(params[:id])
		@course = @term.course
	end

	def show
		@term = current_account.academic_terms.find(params[:id])
		authorize @term
		@course = @term.course
	end

	def update
		@term = current_account.academic_terms.find(params[:id])
		@course = @term.course
		if @term.update(academic_term_params)
			redirect_to @term, notice: "Term has been updated"
		else
			render :edit
		end
	end

	private

	def academic_term_params
		params.require(:academic_term).permit(:title, :code, :term_type, :term_class)
	end
end

app/views/academic_terms/_form.html.erb
<div class="row">
	<%= f.hidden_field :institute_id %>
	<div class="col-sm-6">
		<%= f.input :title, placeholder: 'Term Title' %>
	</div>

	<div class="col-sm-6">
		<%= f.input :code, placeholder: 'Term Code' %>
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
	<%= f.input :term_type, collection: [["Year", "year"], ["Semester", "semester"]], include_blank: false %>
	</div>

	<div class="col-sm-6">
	<%= f.input :term_class, collection: 0..12, include_blank: false %>
	</div>
</div>

app/views/academic_terms/edit.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li> <%= link_to 'Settings', dashboards_path %> </li>
	  <li> <%= link_to 'Courses', courses_path %> </li>
	  <li> <%= link_to @course.name, course_path(@course) %> </li>
	  <li class="active"><%= @term.title %></li>
	</ol>
<% end %>

<div class="row">
	<div class="col-md-8">
  	<%= simple_form_for(@term, layout: :horizontal) do |f| %>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">Editing <%= @term.title %></h3>
			  </div>
			  <div class="panel-body">
			  	<%= render "form", f: f %>
			  </div>
			  <div class="panel-footer">
			  	<%= f.button :submit, 'Add Term' %>
			  </div>
			</div>
	  	<% end %>
	</div>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Some title</h3>
			</div>

			<div class="panel-body">
				Some help text
			</div>
		</div>
	</div>
</div>

app/views/academic_terms/new.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li> <%= link_to 'Settings', dashboards_path %> </li>
	  <li> <%= link_to 'Courses', courses_path %> </li>
	  <li> <%= link_to @course.name, course_path(@course) %> </li>
	  <li class="active">New Term</li>
	</ol>
<% end %>

<div class="row">
	<div class="col-md-8">
  	<%= bootstrap_form_for([@course, @term], layout: :horizontal) do |f| %>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">Add New Term</h3>
			  </div>
			  <div class="panel-body">
			  	<%= render "form", f: f %>
			  </div>
			  <div class="panel-footer">
			  	<%= f.submit 'Add Term' %>
			  </div>
			</div>
	  	<% end %>
	</div>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Some title</h3>
			</div>

			<div class="panel-body">
				Some help text
			</div>
		</div>
	</div>
</div>

app/views/academic_terms/show.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li> <%= link_to 'Settings', dashboards_path %> </li>
	  <li> <%= link_to 'Courses', courses_path %> </li>
	  <li> <%= link_to @course.name, course_path(@course) %> </li>
	  <li class="active"><%= @term.title %></li>
	</ol>
<% end %>

<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title"><%= @term.title %></h3>
		  </div>
		  <div class="panel-heading">Subjects</div>
			<table class="table table-condensed">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th>Code</th>
						<th>Teaching Hours</th>
						<th>Weightage</th>
						<th>Grade Points</th>
						<th>Status</th>
					</tr>
				</thead>

				<tbody>
					<% @term.course_subjects.each_with_index do |subject, index| %>
					<tr>
						<td> <%= index + 1 %> </td>
						<td> <%= link_to subject.title, subject %> </td>
						<td> <%= subject.code %> </td>
						<td> <%= subject.teaching_hours %> </td>
						<td> <%= subject.weightage %> </td>
						<td> <%= subject.grade_points %> </td>
						<td> <%= subject.active ? "Active" : "Inactive" %> </td>
					</tr>
					<% end %>
				</tbody>
			</table>
		  <div class="panel-footer">
		  	<%= link_to '[+ Subject]', new_academic_term_course_subject_path(@term) %>
		  </div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><%= @term.title %></h3>
			</div>

			<div class="panel-body">
				<div class="list-group">
			    <h5 class="list-group-item-heading">Code</h5>
			    <p class="list-group-item-text"><%= @term.code %></p>
				</div>

				<div class="list-group">
			    <h5 class="list-group-item-heading">Term Type</h5>
			    <p class="list-group-item-text"><%= @term.term_type.humanize %></p>
				</div>

				<div class="list-group">
			    <h5 class="list-group-item-heading">Term Class</h5>
			    <p class="list-group-item-text"><%= @term.term_class %></p>
				</div>
			</div>

			<div class="panel-footer">
		  	<%= link_to 'Edit Term', edit_academic_term_path(@term) %>
			</div>
		</div>
	</div>
</div>