config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :dashboards, only: :index

  resources :courses, shallow: true do
    resources :academic_terms do
      resources :course_subjects do
        resources :tutorials do
          resources :assessments do
            resources :tasks do
              resources :marks, only: [:edit, :update]
            end
            resources :grades, only: :update
          end
        end
      end
    end

    resources :course_sessions do
      resources :class_groups
      resources :admissions, only: [:new, :create]
    end
  end

  resources :admissions, only: :index
  resources :students, except: [:new, :create]

  resources :teachers
  resources :people

  class NewSpeakMain
    def self.matches?(request)
      request.host.match /\A(www.|)newspeak.com\z/i
    end
  end

  constraints NewSpeakMain do
    resources :accounts, only: [:new, :create]
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	skip_after_action :verify_policy_scoped
  def index
  	authorize :dashboard, :index?
  	@type = current_user.role.try(:downcase)
  end
end

app/views/dashboards/_default.html.erb
<ul>
	<li> <%= link_to 'People', people_path %> </li>
	<li> <%= link_to 'Courses', courses_path %> </li>
	<li> <%#= link_to 'Admissions', admissions_path %> </li>
	<li> <%= link_to 'Teachers', teachers_path %> </li>
	<li> <%= link_to 'Students', students_path %> </li>
</ul>

app/views/dashboards/_manager.html.erb
<ul>
	<li> <%= link_to 'People', people_path %> </li>
	<li> <%= link_to 'Courses', courses_path %> </li>
	<li> <%= link_to 'Admissions', admissions_path %> </li>
	<li> <%= link_to 'Teachers', teachers_path %> </li>
	<li> <%= link_to 'Students', students_path %> </li>
</ul>

app/views/dashboards/_teacher.html.erb
<div class="col-sm-12">
	<ul>
		<li> <%= link_to 'Teachers', teachers_path %> </li>
		<li> <%= link_to 'Students', students_path %> </li>
	</ul>
</div>

<div class="col-sm-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">My Classes</h3>
		</div>

		<table class="table table-condensed">
			<thead>
				<tr>
					<th>#</th>
					<th>Subject</th>
					<th>Class Group</th>
					<th>Course Session</th>
				</tr>
			</thead>

			<tbody>
				<% current_user.tutorials.each_with_index do |assignment, index| %>
					<tr>
						<td><%= index + 1 %></td>
						<td><%= link_to assignment.course_subject.title, assignment %></td>
						<td><%= assignment.class_group.name %></td>
						<td><%= assignment.class_group.course_session.name %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/dashboards/index.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li class="active">Settings</li>
	</ol>
<% end %>

<div class="row">
	<%= render @type %>
</div>