config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :dashboards, only: :index

  resources :courses, shallow: true do
    resources :academic_terms do
      resources :course_subjects do
        resources :tutorials do
          resources :assessments do
            resources :tasks do
              resources :marks, only: [:edit, :update]
            end
            resources :grades, only: :update
          end
        end
      end
    end

    resources :course_sessions do
      resources :class_groups
      resources :admissions, only: [:new, :create]
    end
  end

  resources :admissions, only: :index
  resources :students, except: [:new, :create]

  resources :teachers
  resources :people

  class NewSpeakMain
    def self.matches?(request)
      request.host.match /\A(www.|)newspeak.com\z/i
    end
  end

  constraints NewSpeakMain do
    resources :accounts, only: [:new, :create]
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  def index
  	@courses = policy_scope(Course)
    authorize @courses
  end

  def new
    @course = current_account.courses.build
    2.times { @course.academic_terms.build(institute: current_account) }
    authorize @course
  end

  def create
    @course = current_account.courses.build(course_params)
    authorize @course
    if @course.save
      redirect_to courses_path, notice: "New course #{@course.name} created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @course = current_account.courses.find(params[:id])
    authorize @course
  end

  private

  def course_params
  	params.require(:course).permit(:name, :abbreviation,
  		academic_terms_attributes: [:title, :code, :term_type, :term_class ,:institute_id])
  end
end

app/views/courses/index.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li> <%= link_to 'Settings', dashboards_path %> </li>
	  <li class="active">Courses</li>
	</ol>
<% end %>

<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default">
		  <div class="panel-heading">All Courses</div>

			<table class="table table-condensed">
				<thead>
					<tr>
						<th>#</th>
						<th>Course Name</th>
						<th>Terms</th>
						<th>Total Sessions</th>
						<th>Action</th>
					</tr>
				</thead>

				<tbody>
					<% @courses.each_with_index do |course, index| %>
					<tr>
						<td> <%= index + 1 %> </td>
						<td> <%= link_to course.name, course %> </td>
						<td> <%= course.academic_terms.length %> </td>
						<td> <%= course.course_sessions.length %> </td>
						<td>
							<%= link_to '[+ Session]', new_course_course_session_path(course) %>
							<%= link_to '[+ Term]', new_course_academic_term_path(course) %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<div class="panel-footer">
				<% if policy(Course).new? %>
					<%= link_to 'New Course', new_course_path %>
				<% end %>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Some title</h3>
			</div>

			<div class="panel-body">
				Some help text
			</div>
		</div>
	</div>
</div>

app/views/courses/new.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li> <%= link_to 'Settings', dashboards_path %> </li>
	  <li> <%= link_to 'Courses', courses_path %> </li>
	  <li class="active">New Course</li>
	</ol>
<% end %>

<div class="row">
	<div class="col-md-8">
  	<%= simple_form_for(@course, layout: :horizontal) do |f| %>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">Add New Course</h3>
			  </div>
			  <div class="panel-body">
	  			<div class="row">
	  				<div class="col-sm-8">
				  		<%= f.input :name, placeholder: 'New Course Name' %>
	  				</div>

	  				<div class="col-sm-4">
				  		<%= f.input :abbreviation, placeholder: 'Course Abbreviation' %>
	  				</div>
	  			</div>

		  		<%= f.fields_for :academic_terms do |tf| %>
			  		<div class="row">
			  			<div class="col-sm-12">
			  				<div class="well well-sm">Term #<%= tf.index + 1 %></div>
			  			</div>
			  		</div>
		  			<div class="row" id="term-<%= tf.index+1 %>">
		  				<div class="col-sm-12">
			  				<%= render "academic_terms/form", f: tf %>
		  				</div>
		  			</div>
		  		<% end %>

			  </div>
			  <div class="panel-footer">
			  	<%= f.button :submit, 'Add Course' %>
			  </div>
			</div>
	  	<% end %>
	</div>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Some title</h3>
			</div>

			<div class="panel-body">
				Some help text
			</div>
		</div>
	</div>
</div>

app/views/courses/show.html.erb
<%= content_for(:breadcrumb) do %>
	<ol class="breadcrumb">
	  <li> <%= link_to 'Settings', dashboards_path %> </li>
	  <li> <%= link_to 'Courses', courses_path %> </li>
	  <li class="active"><%= @course.name %></li>
	</ol>
<% end %>

<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default">
		  <div class="panel-heading">
		  	<h3 class="panel-title">
		  		<%= @course.name %> (<%= @course.abbreviation %>)
	  		</h3>
  		</div>

			<div class="panel-heading">Course Sessions</div>
			<table class="table table-condensed">
				<thead>
					<tr>
						<th>#</th>
						<th>Session Name</th>
						<th>Current Term</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Action</th>
						<th>Class Groups</th>
					</tr>
				</thead>

				<tbody>
					<% @course.course_sessions.each_with_index do |session, index| %>
					<tr>
						<td> <%= index + 1 %> </td>
						<td> <%= link_to session.name, course_session_path(session) %> </td>
						<td> <%= session.current_term.title %> </td>
						<td> <%= session.start_date.to_formatted_s(:rfc822) %> </td>
						<td> <%= session.end_date.to_formatted_s(:rfc822) %> </td>
						<td> <%= link_to "Edit", edit_course_session_path(session) %> </td>
						<td> 
							<% session.class_groups.each do |group| %>
								<%= link_to group do %>
									<span class="primary-label"><%= group.name %></span>
								<% end %>
							<% end %>
							<%= link_to new_course_session_class_group_path(session)  do %>
								<span class="success-label">+</span>
							<% end %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<div class="panel-heading">Terms</div>

			<div class="panel-body">
				<div class="row">
					<div class="col-sm-12">
					<dl class="dl-horizontal">
						<% @course.academic_terms.each do |term| %>
							<dt><%= link_to term.title, term %></dt>
							<dd><%= raw term.course_subjects.collect { |subject| link_to subject.title, subject }.join(", ") %></dd>
						<% end %>
					</dl>
					</div>
				</div>
			</div>

			<div class="panel-footer">
				<% if policy(CourseSession).new? %>
					<%= link_to '[+ Session]', new_course_course_session_path(@course) %>
				<% end %>
				<%= link_to '[+ Term]', new_course_academic_term_path(@course) %>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Last Session - Summary</h3>
			</div>

			<div class="panel-body">
				Some help text
			</div>
		</div>
	</div>
</div>